// RAGService.swift
// On-device retrieval-augmented generation for the four educational
// subjects (geology, plants, physics, english).
//
// PIPELINE
// --------
// 1. User question  →  embed(query) via MiniLM (swift-embeddings / MLTensor)
// 2. Cosine-similarity search against the active subject's pre-embedded
//    corpus (chunks + embeddings.f16 from `rag-poc/`)
// 3. Top-k chunks returned to the caller for prompt injection
//
// MEMORY MODEL
// ------------
// The embedding model loads lazily on first use (~40 MB resident at
// FP16, routes to Neural Engine when available). Active subject's
// embeddings are loaded into RAM as Float arrays — at PoC scale (~25
// chunks × 384 dims × 4 bytes ≈ 40 KB per subject) this is rounding
// error. For 50K-chunk production corpora we would mmap the f16 blob
// instead of loading into RAM; the API doesn't change.
//
// FIRST-LAUNCH NETWORK REQUIREMENT
// --------------------------------
// `swift-embeddings`' `Bert.loadModelBundle(from: "...")` downloads
// the model from Hugging Face on first use and caches in the app's
// sandbox Caches directory. Subsequent launches are fully offline.
// For a strict offline-from-day-one experience we would pre-bundle
// the model files in `Resources/Models/MiniLM/` and point at the
// local URL form — deferred until the PoC ships.
//
// BUNDLE LAYOUT EXPECTED
// ----------------------
//   Resources/RAG/<subject>.jsonl
//   Resources/RAG/<subject>.embeddings.f16
//   Resources/RAG/manifest.json
// Generated by:
//   $ python3 scripts/embed-rag-corpus.py
// then dragged into the Xcode project as a folder reference.

import Foundation
import Combine

#if canImport(Embeddings)
import Embeddings
#endif

@MainActor
final class RAGService: ObservableObject {

    // MARK: - Subjects

    enum Subject: String, CaseIterable, Identifiable, Codable {
        case geology
        case plants
        case physics
        case english

        var id: String { rawValue }

        var displayName: String {
            switch self {
            case .geology: return "Geology"
            case .plants:  return "Plants"
            case .physics: return "Physics"
            case .english: return "English"
            }
        }
    }

    // MARK: - Published state

    @Published private(set) var status: String = "RAG idle"
    @Published private(set) var activeSubject: Subject?
    @Published private(set) var isModelLoaded: Bool = false
    @Published private(set) var isCorpusLoaded: Bool = false

    // MARK: - Internals

    /// Name of the bundled embedder directory under
    /// `Resources/Models/MiniLM/`. The model is shipped IN-APP rather
    /// than downloaded from HuggingFace at runtime — we accepted the
    /// ~87 MB bundle-size hit (small next to Gemma + Kokoro) in
    /// exchange for offline-from-install behavior and no first-run
    /// network requirement. See `scripts/fetch-models.sh` for the
    /// fetch logic that populates this directory on fresh clones.
    private let embedderBundleSubdir = "MiniLM"

    /// Embedding dimension produced by `all-MiniLM-L6-v2`. Hard-coded
    /// here to avoid asserting against a freshly-loaded model. If we
    /// ever swap in a different embedder, update this AND re-embed
    /// the corpus from scratch with `scripts/embed-rag-corpus.py`.
    private let embeddingDim = 384

    #if canImport(Embeddings)
    /// Lazily-loaded model. Nil until first `embed(_:)` call.
    /// Holding it onto the type via `Any?` so the file still compiles
    /// before the SPM dep resolves on a fresh `xcodegen` pass.
    private var modelBundle: Bert.ModelBundle?
    #else
    private var modelBundle: Any?
    #endif

    /// Active subject's chunks, parallel-indexed with `activeEmbeddings`.
    private var activeChunks: [RAGChunk] = []

    /// Float32 vectors for each chunk in the active subject. Outer
    /// array index matches `activeChunks`; inner array length is
    /// `embeddingDim` (L2-normalized at ingest time so cosine-sim is
    /// just a dot product at retrieval).
    private var activeEmbeddings: [[Float]] = []

    // MARK: - Public API

    /// Set the active subject. Loads its corpus from the app bundle
    /// (synchronous, fast — small file I/O) but does NOT load the
    /// embedding model — that happens lazily on the first `retrieve`
    /// call to avoid paying the cost when the user opens a subject
    /// they don't end up querying.
    ///
    /// Pass `nil` to clear. Idempotent if `subject` matches the
    /// already-active one.
    func setActiveSubject(_ subject: Subject?) throws {
        if subject == activeSubject { return }
        activeSubject = subject
        guard let subject else {
            activeChunks = []
            activeEmbeddings = []
            isCorpusLoaded = false
            status = "RAG idle"
            print("[RAG] activeSubject cleared")
            return
        }
        try loadCorpus(for: subject)
        print("[RAG] activeSubject = \(subject.rawValue), \(activeChunks.count) chunks loaded")
    }

    /// Eagerly download + load the embedding model. Called from
    /// `ContentView.task` at app launch so the ~80 MB MiniLM HF
    /// download happens in the background before the user takes
    /// their first Ask. Subsequent retrievals see a hot model.
    ///
    /// Safe to call multiple times — `ensureModelLoaded` is
    /// idempotent. Failures are logged; retrieval will retry on
    /// next call.
    func preload() async throws {
        print("[RAG] preload start")
        try await ensureModelLoaded()
        print("[RAG] preload done")
    }

    /// Retrieve top-k chunks most semantically similar to `query`.
    /// Triggers lazy load of the embedding model on first call.
    /// Returns an empty array if no subject is active.
    ///
    /// - Parameters:
    ///   - query: natural-language question text
    ///   - k: number of chunks to return (default 1; ADR caps at 2)
    func retrieve(query: String, k: Int = 1) async throws -> [RAGChunk] {
        guard let subject = activeSubject else {
            print("[RAG] retrieve skipped: no active subject")
            return []
        }
        guard !activeChunks.isEmpty else {
            print("[RAG] retrieve skipped: corpus empty for \(subject.rawValue)")
            return []
        }
        guard !query.isEmpty else {
            print("[RAG] retrieve skipped: empty query")
            return []
        }
        print("[RAG] retrieve subject=\(subject.rawValue) k=\(k) q=\"\(query.prefix(80))\"")

        try await ensureModelLoaded()
        let queryVec = try await embed(query)

        // Brute-force cosine similarity. Both query and chunk vectors
        // are L2-normalized, so cosine == dot product.
        // For 25 chunks × 384 dims this is ~10K multiplies — under a
        // millisecond. Swap for ANN at >10K chunks.
        var ranked: [(idx: Int, score: Float)] = []
        ranked.reserveCapacity(activeChunks.count)
        for (i, chunkVec) in activeEmbeddings.enumerated() {
            ranked.append((i, dot(queryVec, chunkVec)))
        }
        ranked.sort { $0.score > $1.score }
        let topK = ranked.prefix(k).map { activeChunks[$0.idx] }
        if let top = ranked.first {
            let chunk = activeChunks[top.idx]
            print("[RAG] top: \(chunk.id) \"\(chunk.title)\" score=\(String(format: "%.3f", top.score))")
        }
        return Array(topK)
    }

    /// Embed a single string. Public for callers that want to embed
    /// without retrieving (e.g. semantic memory for conversation).
    /// Returns an L2-normalized Float32 vector of length `embeddingDim`.
    func embed(_ text: String) async throws -> [Float] {
        try await ensureModelLoaded()
        #if canImport(Embeddings)
        guard let bundle = modelBundle else {
            throw RAGError.modelMissing
        }
        let tensor = try bundle.encode(text)
        // MLTensor → [Float]. `shapedArray` is async — it triggers
        // backend compute and materializes the result into a typed
        // array. Shape is [embeddingDim] for `encode`; [N, dim] for
        // `batchEncode`.
        let array = await tensor.shapedArray(of: Float.self)
        var scalars = Array(array.scalars)
        if scalars.count != embeddingDim {
            // If swift-embeddings ever returns a 2-D [1, dim] shape
            // for single-input encode, flatten here.
            if scalars.count > embeddingDim {
                scalars = Array(scalars.prefix(embeddingDim))
            }
        }
        // Defensive L2 normalize. swift-embeddings already mean-pools
        // and normalizes for sentence-transformer-style models, but
        // we don't want to depend on that contract for retrieval
        // correctness — the dot-product math assumes unit vectors.
        return l2Normalize(scalars)
        #else
        // Build path where the SPM dep hasn't resolved yet (fresh
        // checkout pre-`xcodegen`). Surface a clear error rather
        // than silently returning zeros.
        throw RAGError.dependencyNotResolved
        #endif
    }

    /// Drop the embedding model from memory. Conversation can resume
    /// with `setActiveSubject(...)` — model reloads on next retrieve.
    /// Useful if we ever observe memory pressure during Gemma generation
    /// (the embedder is small enough that this is rarely needed in
    /// practice, but keep the lever).
    func unloadModel() {
        modelBundle = nil
        isModelLoaded = false
        status = "Embedder unloaded"
    }

    /// Format retrieved chunks as a `[REFERENCE — Subject]` block ready
    /// to drop into Gemma's user prompt (via `gemma.ragContext`).
    /// Returns the empty string for empty input so callers can blindly
    /// pass through to `gemma.ragContext` without branching.
    ///
    /// Chunk text is used (not summary) — at PoC scale we have token
    /// budget. If we need to tighten later, swap `c.text` for
    /// `c.summary` and re-measure on device.
    func formatChunksForPrompt(_ chunks: [RAGChunk]) -> String {
        guard !chunks.isEmpty else { return "" }
        guard let subject = activeSubject else { return "" }
        var lines: [String] = [
            "[REFERENCE — \(subject.displayName)]",
        ]
        for c in chunks {
            lines.append("(\(c.title)) \(c.text)")
        }
        lines.append("[/REFERENCE]")
        return lines.joined(separator: "\n")
    }

    // MARK: - Internals

    private func ensureModelLoaded() async throws {
        if modelBundle != nil { return }
        #if canImport(Embeddings)
        status = "Loading embedder…"

        // Resolve the bundled model directory.
        // Bundle.main.url(forResource:) requires a specific file inside
        // the folder reference, so we look for config.json and walk up.
        guard let configURL = Bundle.main.url(
                forResource: "config",
                withExtension: "json",
                subdirectory: "Models/\(embedderBundleSubdir)")
        else {
            print("[RAG] embedder load FAILED: bundle missing Models/\(embedderBundleSubdir)/config.json")
            throw RAGError.modelLoadFailed(
                NSError(
                    domain: "RAGService",
                    code: -1,
                    userInfo: [NSLocalizedDescriptionKey:
                        "MiniLM not in app bundle at Models/\(embedderBundleSubdir)/. " +
                        "Run scripts/fetch-models.sh and rebuild."]
                )
            )
        }
        let modelFolder = configURL.deletingLastPathComponent()
        print("[RAG] loading embedder from \(modelFolder.path) ...")

        do {
            let t0 = Date()
            modelBundle = try await Bert.loadModelBundle(from: modelFolder)
            isModelLoaded = true
            status = "Embedder ready"
            let elapsed = Date().timeIntervalSince(t0)
            print(String(format: "[RAG] embedder ready (%.2fs)", elapsed))
        } catch {
            status = "Embedder load failed: \(error.localizedDescription)"
            print("[RAG] embedder load FAILED: \(error.localizedDescription)")
            throw RAGError.modelLoadFailed(error)
        }
        #else
        throw RAGError.dependencyNotResolved
        #endif
    }

    private func loadCorpus(for subject: Subject) throws {
        status = "Loading \(subject.displayName) corpus…"

        guard let chunksURL = Bundle.main.url(
                forResource: subject.rawValue,
                withExtension: "jsonl",
                subdirectory: "RAG")
        else {
            throw RAGError.corpusMissing(subject, "chunks.jsonl")
        }
        guard let embeddingsURL = Bundle.main.url(
                forResource: subject.rawValue,
                withExtension: "embeddings.f16",
                subdirectory: "RAG")
        else {
            throw RAGError.corpusMissing(subject, "embeddings.f16")
        }

        // 1) Decode chunks.jsonl
        let chunksText = try String(contentsOf: chunksURL, encoding: .utf8)
        var chunks: [RAGChunk] = []
        let decoder = JSONDecoder()
        for line in chunksText.split(separator: "\n", omittingEmptySubsequences: true) {
            let data = Data(line.utf8)
            chunks.append(try decoder.decode(RAGChunk.self, from: data))
        }

        // 2) Decode embeddings blob (raw float16, [N × dim], little-endian).
        //    Convert to float32 here for fast dot products in Swift —
        //    cheap (~40 KB at PoC scale).
        let blob = try Data(contentsOf: embeddingsURL)
        let f16Count = blob.count / 2
        if f16Count != chunks.count * embeddingDim {
            throw RAGError.corpusMismatch(
                subject: subject,
                chunkCount: chunks.count,
                expectedFloats: chunks.count * embeddingDim,
                actualFloats: f16Count
            )
        }
        var f32Flat = [Float](repeating: 0, count: f16Count)
        blob.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            let f16Ptr = raw.bindMemory(to: Float16.self)
            for i in 0..<f16Count {
                f32Flat[i] = Float(f16Ptr[i])
            }
        }
        var embeddings: [[Float]] = []
        embeddings.reserveCapacity(chunks.count)
        for chunkIdx in 0..<chunks.count {
            let start = chunkIdx * embeddingDim
            embeddings.append(Array(f32Flat[start..<(start + embeddingDim)]))
        }

        activeChunks = chunks
        activeEmbeddings = embeddings
        isCorpusLoaded = true
        status = "\(subject.displayName) ready · \(chunks.count) chunks"
    }
}

// MARK: - Pure helpers

private func dot(_ a: [Float], _ b: [Float]) -> Float {
    let n = min(a.count, b.count)
    var sum: Float = 0
    for i in 0..<n {
        sum += a[i] * b[i]
    }
    return sum
}

private func l2Normalize(_ v: [Float]) -> [Float] {
    var sumSq: Float = 0
    for x in v { sumSq += x * x }
    let norm = sumSq.squareRoot()
    if norm == 0 { return v }
    return v.map { $0 / norm }
}

// MARK: - Chunk model

/// Mirror of the JSONL schema in `rag-poc/README.md`. Decoder is
/// permissive — extra fields are ignored.
struct RAGChunk: Codable, Identifiable, Equatable {
    let id: String
    let subject: String
    let title: String
    let text: String
    let summary: String
    let tags: [String]
    let region: String
    let source: String
}

// MARK: - Errors

enum RAGError: LocalizedError {
    case dependencyNotResolved
    case modelMissing
    case modelLoadFailed(Error)
    case corpusMissing(RAGService.Subject, String)
    case corpusMismatch(subject: RAGService.Subject,
                        chunkCount: Int,
                        expectedFloats: Int,
                        actualFloats: Int)

    var errorDescription: String? {
        switch self {
        case .dependencyNotResolved:
            return "swift-embeddings package not yet resolved. Run scripts/generate-project.sh and rebuild."
        case .modelMissing:
            return "Embedding model not loaded."
        case .modelLoadFailed(let err):
            return "Failed to load embedding model: \(err.localizedDescription)"
        case .corpusMissing(let subject, let file):
            return "Missing \(file) for subject \(subject.rawValue) in app bundle (Resources/RAG/)."
        case .corpusMismatch(let subject, let chunks, let expected, let actual):
            return "Corpus size mismatch for \(subject.rawValue): \(chunks) chunks expect \(expected) floats, got \(actual)."
        }
    }
}
